import type { TrackRecord } from "../types";

export const DEMO_TRACK_RECORD: TrackRecord = {
  accuracy: 0.741,
  brierScore: 0.146,
  marketBrierScore: 0.178,
  resolvedCount: 214,
  calibrationError: 0.031,
  buckets: [
    { predicted: 0.05, actual: 0.04, count: 21 },
    { predicted: 0.15, actual: 0.13, count: 26 },
    { predicted: 0.25, actual: 0.28, count: 24 },
    { predicted: 0.35, actual: 0.33, count: 23 },
    { predicted: 0.45, actual: 0.47, count: 19 },
    { predicted: 0.55, actual: 0.52, count: 22 },
    { predicted: 0.65, actual: 0.69, count: 25 },
    { predicted: 0.75, actual: 0.72, count: 20 },
    { predicted: 0.85, actual: 0.88, count: 18 },
    { predicted: 0.95, actual: 0.92, count: 16 },
  ],
  leaderboard: [
    {
      id: "combined",
      name: "Combined Contrary",
      brierScore: 0.146,
      accuracy: 0.741,
      resolved: 214,
      trend: -0.008,
    },
    {
      id: "contrarian",
      name: "Contrarian Agent",
      brierScore: 0.163,
      accuracy: 0.706,
      resolved: 214,
      trend: -0.011,
    },
    {
      id: "market-consensus",
      name: "Market Consensus",
      brierScore: 0.178,
      accuracy: 0.692,
      resolved: 214,
      trend: 0.002,
    },
    {
      id: "news",
      name: "News Agent",
      brierScore: 0.181,
      accuracy: 0.687,
      resolved: 214,
      trend: -0.004,
    },
    {
      id: "base-rate",
      name: "Base Rate Agent",
      brierScore: 0.189,
      accuracy: 0.673,
      resolved: 214,
      trend: 0.001,
    },
    {
      id: "skeptic",
      name: "Skeptic Agent",
      brierScore: 0.194,
      accuracy: 0.668,
      resolved: 214,
      trend: -0.006,
    },
    {
      id: "market",
      name: "Market Analyst Agent",
      brierScore: 0.202,
      accuracy: 0.654,
      resolved: 214,
      trend: 0.003,
    },
  ],
  recent: [
    {
      id: "r1",
      question: "Will a major lab release an open-weights reasoning model in H1 2026?",
      category: "AI",
      resolvedOn: "2026-07-02",
      outcome: "YES",
      marketProbability: 54,
      contraryProbability: 71,
    },
    {
      id: "r2",
      question: "Will the ECB raise rates at its June 2026 meeting?",
      category: "Economy",
      resolvedOn: "2026-06-19",
      outcome: "NO",
      marketProbability: 34,
      contraryProbability: 17,
    },
    {
      id: "r3",
      question: "Will a private lunar lander complete a soft landing by June 2026?",
      category: "Science",
      resolvedOn: "2026-06-04",
      outcome: "YES",
      marketProbability: 68,
      contraryProbability: 74,
    },
    {
      id: "r4",
      question: "Will a US state pass comprehensive AI liability legislation by May 2026?",
      category: "Technology",
      resolvedOn: "2026-05-21",
      outcome: "NO",
      marketProbability: 61,
      contraryProbability: 38,
    },
    {
      id: "r5",
      question: "Will global streaming subscriptions decline year over year in Q1 2026?",
      category: "Culture",
      resolvedOn: "2026-04-28",
      outcome: "NO",
      marketProbability: 29,
      contraryProbability: 21,
    },
    {
      id: "r6",
      question: "Will a chip fabrication plant break ground in the EU before April 2026?",
      category: "Technology",
      resolvedOn: "2026-04-09",
      outcome: "YES",
      marketProbability: 77,
      contraryProbability: 82,
    },
    {
      id: "r7",
      question: "Will unemployment exceed 5% in any G7 country in Q1 2026?",
      category: "Economy",
      resolvedOn: "2026-04-02",
      outcome: "YES",
      marketProbability: 45,
      contraryProbability: 63,
    },
    {
      id: "r8",
      question: "Will an AI system win a gold medal at a major olympiad in 2026?",
      category: "AI",
      resolvedOn: "2026-03-15",
      outcome: "YES",
      marketProbability: 72,
      contraryProbability: 66,
    },
  ],
};
